# inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/seeds/**/*'
    - 'vendor/**/*'
    - 'config/initializers/secret_token.rb'
    - 'config/deploy.rb'
    - 'config/routes.rb'
    - 'config/environments/*'
Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - spec/**/*_spec.rb
    - spec/factories/*.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  AutoCorrect: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Style/StringLiterals:
 Enabled: false
